export const metrics = [ ['Treasury', '$0.00'], ['Lifetime Revenue', '$0.00'], ['Live, no fees yet', '2'], ['Works in progress', '2'] ];
export const treasury = [['Treasury value','$0'],['Lifetime revenue','$0'],['Trading fees','$0'],['Product fees','$0'],['Starting value','$0']];
export const products = [
  { id:'readsentence', name:'ReadSentence', status:'LIVE', tone:'green', image:'/assets/readsentence.png', description:'Sentence-by-sentence reading. Live now. Monetisation next.', details:'Already shipped and part of the wider product ecosystem. Monetisation is planned; it does not generate product fees yet.', kind:'image', url:'https://readsentence.com' },
  { id:'degen-karts', name:'Degen Karts', status:'LIVE PROTOTYPE', tone:'green', image:'/assets/degen-karts.png', description:'A live prototype crypto kart game with its own characters and community. The first playable version is already online.', details:'The prototype is live but does not generate product fees yet. The longer-term direction is a custom platform where other communities can launch their own version.', kind:'image', url:'https://kackupa.github.io/DegenKart/' },
  { id:'arb-launchpad', name:'ARB Launchpad', status:'WIP', tone:'yellow', image:'/assets/arb-launchpad.png', description:'Multi-chain token markets with same-chain and cross-chain arbitrage in development.', details:'Planned loop: MULTI-CHAIN POOLS → ARB BOT → TRADING VOLUME → CREATOR FEES. Planned creator-fee split: 70% creator / 30% Srajtaśma. This is not a token transfer tax.', kind:'network', url:'https://kackupa.github.io/SrajPad/' },
  { id:'caesar-engine', name:'Caesar Engine', status:'WIP', tone:'yellow', image:'/assets/caesar-engine.png', description:'A city-builder in progress, with a custom economy, assets and token.', details:'Build a working version first, then make it configurable for other communities. The planned platform cut would feed Srajtaśma; it does not generate product fees yet.', kind:'image' },
  { id:'round-table', name:'The Round Table', status:'PLANNED', tone:'muted', image:'/assets/round-table.jpg', description:'12 agents. Always working the ecosystem.', details:'ATTENTION · RESEARCH · OPPORTUNITIES. Mainly an internal advantage, not a white-label product at this stage.', kind:'agents' }
];
export const agents = Array.from({length:12},(_,i)=>({id:i+1, role:'ROLE TBD'}));
export const buildLog = [{date:'26 SEPTEMBER 2026', items:['KAC KUPA ecosystem model defined','ARB Launchpad architecture defined','Initial products grouped under KAC KUPA','12-agent Round Table added to ecosystem plan','Public shopwindow development started']}];
