export const metrics = [ ['Treasury', '$0.00'], ['Lifetime Revenue', '$0.00'], ['Products Live', '2'], ['Products Building', '1'] ];
export const treasury = [['Treasury value','$0'],['Lifetime revenue','$0'],['Trading fees','$0'],['Product fees','$0'],['Starting value','$0']];
export const products = [
  { id:'readsentence', name:'ReadSentence', status:'LIVE', tone:'green', image:'/assets/readsentence.jpg', description:'Sentence-by-sentence reading. Live now. Monetisation next.', details:'Already shipped and part of the wider product ecosystem. It is planned to be monetised soon; it is not currently counted as Srajtaśma revenue.', kind:'image', url:'https://readsentence.com' },
  { id:'degen-karts', name:'Degen Karts', status:'LIVE', tone:'green', image:'/assets/degen-karts.jpg', description:'A live MVP crypto kart game with its own characters and community. The first playable version is already online.', details:'The MVP is live. The longer-term direction is a custom platform where other communities can launch their own version.', kind:'image', url:'https://kackupa.github.io/DegenKart/' },
  { id:'arb-launchpad', name:'ARB Launchpad', status:'BUILDING', tone:'green', image:'/assets/arb-launchpad.png', description:'Multi-chain token markets with same-chain and cross-chain arbitrage built in.', details:'MULTI-CHAIN POOLS → ARB BOT → TRADING VOLUME → CREATOR FEES. Platform-controlled creator-fee revenue: 70% creator / 30% Srajtaśma. This is not a token transfer tax.', kind:'network' },
  { id:'caesar-engine', name:'Caesar Engine', status:'PROTOTYPE', tone:'yellow', image:'/assets/caesar-engine.jpg', description:'Build a custom city-builder world with your own economy, assets and token.', details:'We build ours first, then other communities can customise their own version. Platform revenue feeds Srajtaśma.', kind:'image' },
  { id:'round-table', name:'The Round Table', status:'PLANNED', tone:'muted', image:'/assets/round-table.jpg', description:'12 agents. Always working the ecosystem.', details:'ATTENTION · RESEARCH · OPPORTUNITIES. Mainly an internal advantage, not a white-label product at this stage.', kind:'agents' }
];
export const agents = Array.from({length:12},(_,i)=>({id:i+1, role:'ROLE TBD'}));
export const buildLog = [{date:'26 SEPTEMBER 2026', items:['KAC KUPA ecosystem model defined','ARB Launchpad architecture defined','Initial products grouped under KAC KUPA','12-agent Round Table added to ecosystem plan','Public shopwindow development started']}];
export const principles = [['BUILD FOR OURSELVES FIRST','We should never need outside users for a product to make sense.'],['PRODUCTISE WHAT WORKS','If something proves useful, make it configurable so others can use it too.'],['TAKE A CUT','The platform earns a cut from products built on its infrastructure.'],['ADD REVENUE ENGINES','Every useful new module can become another source of treasury revenue.'],['KEEP BUILDING','New products can be added without changing the basic thesis.']];
