import React from 'react'; import { createRoot } from 'react-dom/client'; import { ArrowUpRight, Menu, X, Activity, CircleDot } from 'lucide-react'; import {metrics, treasury, products, agents, buildLog, principles} from './data'; import './styles.css';

const Placeholder=({product}:{product:any})=><div className={'visual '+product.kind}>
  <div className="visual-label">PRODUCT SNAPSHOT <span>/{product.image.replace('/assets/','')}</span></div>
  {product.kind==='network'?<><div className="network"><div className="arb-node">ARB<br/><b>BOT</b></div>{['ROBINHOOD CHAIN','BASE','ETHEREUM L1'].map((x,i)=><div className={'chain c'+i} key={x}><i/>{x}<small>KACKUPA MARKET</small></div>)}</div><div className="soon">SOLANA <span>— COMING SOON</span></div></>:product.kind==='agents'?<div className="agent-preview">{agents.slice(0,6).map(a=><span key={a.id}>AGENT {String(a.id).padStart(2,'0')}</span>)}</div>:<div className="empty-shot"><span>SCREENSHOT<br/>PLACEHOLDER</span><small>16:9 / ASSET READY</small></div>}
</div>;
const SectionTitle=({eyebrow,title,children}:{eyebrow:string,title:string,children?:React.ReactNode})=><div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>;
function App(){const [open,setOpen]=React.useState(false); return <><header><a className="brand" href="#top">KAC<span>KUPA</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{[['Products','#products'],['Treasury','#treasury'],['Round Table','#roundtable'],['Build Log','#build-log'],['Docs','#docs']].map(([x,y])=><a href={y} onClick={()=>setOpen(false)} key={x}>{x}</a>)}<a href="https://github.com/kackupa/SIPP" target="_blank">GitHub <ArrowUpRight size={14}/></a></nav></header>
<main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> PUBLIC BUILD / 001</p><h1>Building products that turn on-chain activity into a growing treasury.</h1><p className="lede">Starting from $0. Building my retirement fund one product, trade and fee at a time.</p><p className="join">Come join KAC KUPA — that's me — and retire together.</p><a className="button" href="#products">Explore the build <ArrowUpRight size={16}/></a></div><div className="hero-mark"><span>K</span><span>K</span><small>BUILD / ACTIVITY / FEES</small></div></section>
<section className="metrics">{metrics.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</section>
<section className="flywheel"><p className="eyebrow">THE BASIC IDEA</p><div>{['BUILD','ACTIVITY','FEES','TREASURY','COMPOUND'].map((x,i)=><React.Fragment key={x}><b>{x}</b>{i<4&&<span>→</span>}</React.Fragment>)}</div></section>
<section id="products"><SectionTitle eyebrow="01 / PRODUCTS" title="Built for KAC KUPA first."><p className="side-note">If it works for us, it can become a platform for everyone.</p></SectionTitle><div className="product-grid">{products.map((p,i)=><article className={'product '+(i===0?'featured':'')} key={p.name}><Placeholder product={p}/><div className="product-info"><div><span className={'status '+p.tone}><i/>{p.status}</span><h3>{p.name}</h3></div><p>{p.description}</p><a href="#docs" aria-label={'Read more about '+p.name}>DETAILS <ArrowUpRight size={15}/></a></div></article>)}</div></section>
<section id="treasury" className="treasury"><SectionTitle eyebrow="02 / TREASURY" title="Make this number go up."><p className="side-note">Public by default. Config-driven today, live data later.</p></SectionTitle><div className="treasury-main"><div className="big-number"><span>TREASURY VALUE</span><strong>$0</strong><em>STARTING VALUE: $0</em></div><div className="treasury-list">{treasury.slice(1).map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div></section>
<section className="model"><SectionTitle eyebrow="03 / THE MODEL" title="A simple flywheel."/><div className="steps">{[['01','BUILD FOR OURSELVES','Create something KAC KUPA actually wants to use.'],['02','MAKE IT GENERATE REVENUE','Activity generates fees.'],['03','PRODUCTISE IT','Turn the working system into something other communities can launch or customise.'],['04','TAKE A PLATFORM CUT','Creators and users keep the majority. KAC KUPA receives its platform share.'],['05','GROW THE TREASURY','Every successful module becomes another revenue stream.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>
<section id="roundtable" className="roundtable"><SectionTitle eyebrow="04 / THE ROUND TABLE" title="Twelve seats. Not deployed yet."><p className="side-note">A future internal advantage for keeping the ecosystem active and relevant.</p></SectionTitle><div className="agents">{agents.map(a=><div className="agent" key={a.id}><div className="avatar"><CircleDot/></div><div><b>AGENT {String(a.id).padStart(2,'0')}</b><span>{a.role}</span><small><i/> OFFLINE / NOT DEPLOYED</small></div></div>)}</div></section>
<section id="build-log" className="log"><SectionTitle eyebrow="05 / PUBLIC BUILD LOG" title="Watching it take shape."/><div className="log-entry"><div className="log-date">{buildLog[0].date}</div><div>{buildLog[0].items.map(x=><p key={x}><span>+</span>{x}</p>)}</div></div></section>
<section id="docs" className="docs"><SectionTitle eyebrow="06 / PRINCIPLES" title="The rules of the build."/><div className="principles">{principles.map(([a,b],i)=><div key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div></section>
</main><footer><span>KAC KUPA — starting from $0.</span><a href="https://github.com/kackupa/SIPP" target="_blank">GITHUB <ArrowUpRight size={14}/></a></footer></>}; createRoot(document.getElementById('root')!).render(<App/>);
