import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, CircleDot, Menu, X } from 'lucide-react';
import { agents, buildLog, metrics, products, treasury } from './data';
import './styles.css';
import './overrides.css';

type Product = (typeof products)[number];
const arbRoutes = [
  { out: 'M 721 245 C 643 346 535 272 449 296 S 359 292 323 288', back: 'M 323 288 C 372 282 406 301 449 296 C 535 272 643 346 721 245' },
  { out: 'M 965 283 C 1030 354 1120 252 1260 247 S 1350 251 1382 251', back: 'M 1382 251 C 1335 254 1300 244 1260 247 C 1120 252 1030 354 965 283' },
  { out: 'M 758 451 C 625 487 565 605 444 630 S 304 650 241 648', back: 'M 241 648 C 310 650 365 636 444 630 C 565 605 625 487 758 451' },
  { out: 'M 917 451 C 1049 510 1114 613 1239 637 S 1370 648 1432 646', back: 'M 1432 646 C 1364 649 1290 645 1239 637 C 1114 613 1049 510 917 451' },
];
function ArbArtworkMotion({ src }: { src: string }) {
  return <svg className="arb-art-motion" viewBox="0 0 1672 941" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
    <defs>
      <clipPath id="arb-left-hand"><path d="M 701 211 L 735 210 L 758 256 L 749 278 L 792 317 L 786 339 L 768 336 L 730 291 L 701 281 L 681 250 Z" /></clipPath>
      <clipPath id="arb-right-hand"><path d="M 950 250 L 985 252 L 1004 277 L 998 310 L 971 326 L 941 312 L 912 339 L 896 327 L 931 281 Z" /></clipPath>
    </defs>
    <g className="arb-arm-flick arb-arm-left"><image href={src} width="1672" height="941" clipPath="url(#arb-left-hand)" /></g>
    <g className="arb-arm-flick arb-arm-right"><image href={src} width="1672" height="941" clipPath="url(#arb-right-hand)" /></g>
    <g className="arb-toss arb-toss-left"><rect x="-21" y="-24" width="42" height="48" rx="12" /><ellipse cx="0" cy="-18" rx="15" ry="7" className="arb-toss-end" /><ellipse cx="0" cy="-18" rx="6" ry="3" className="arb-packet-hole" /><animateMotion dur="3.8s" repeatCount="indefinite" calcMode="linear" keyPoints="0;1;1" keyTimes="0;.3;1" path="M 720 236 Q 621 138 552 302" /></g>
    <g className="arb-toss arb-toss-right"><rect x="-21" y="-24" width="42" height="48" rx="12" /><ellipse cx="0" cy="-18" rx="15" ry="7" className="arb-toss-end" /><ellipse cx="0" cy="-18" rx="6" ry="3" className="arb-packet-hole" /><animateMotion dur="4.15s" begin=".7s" repeatCount="indefinite" calcMode="linear" keyPoints="0;1;1" keyTimes="0;.3;1" path="M 965 282 Q 1064 157 1126 276" /></g>
    {arbRoutes.map((route, index) => <React.Fragment key={route.out}>
      <path className="arb-trace" d={route.out} />
      <g className="arb-packet arb-packet-out"><rect x="-15" y="-11" width="30" height="22" rx="5" /><ellipse cx="8" rx="4" ry="7" className="arb-packet-hole" /><animateMotion dur={`${3.8 + index * .35}s`} begin={`${index * .7}s`} repeatCount="indefinite" path={route.out} /></g>
      <g className="arb-packet arb-packet-return"><rect x="-10" y="-8" width="20" height="16" rx="4" /><ellipse cx="5" rx="3" ry="5" className="arb-packet-hole" /><animateMotion dur={`${5.4 + index * .45}s`} begin={`${index * .9}s`} repeatCount="indefinite" path={route.back} /></g>
    </React.Fragment>)}
    <g className="arb-throw arb-throw-left"><circle cx="722" cy="246" r="13" /><path d="M 701 250 L 690 250 M 718 224 L 718 214 M 742 239 L 752 234" /></g>
    <g className="arb-throw arb-throw-right"><circle cx="965" cy="287" r="13" /><path d="M 986 291 L 997 291 M 967 265 L 967 255 M 944 278 L 934 273" /></g>
    {[['robinhood', 323, 288], ['base', 1382, 251], ['solana', 241, 648], ['ethereum', 1432, 646]].map(([chain, x, y]) => <circle className={`arb-arrival arb-arrival-${chain}`} key={chain} cx={x} cy={y} r="53" />)}
  </svg>;
}
function ProductVisual({ product }: { product: Product }) {
  const [visible, setVisible] = React.useState(true);
  const src = `${import.meta.env.BASE_URL}${product.image.replace(/^\//, '')}`;
  return <div className={'visual ' + product.kind + ' ' + product.id + (visible && product.kind === 'network' ? ' has-image' : '')}>
    {!visible && <div className="visual-label">PRODUCT SNAPSHOT <span>/{product.image.replace('/assets/', '')}</span></div>}
    {visible && <img className="product-image" src={src} alt={`${product.name} preview`} onError={() => setVisible(false)} />}
    {visible && product.kind === 'network' && <ArbArtworkMotion src={src} />}
    {!visible && product.kind === 'network' && <div className="empty-shot"><span>ARB LAUNCHPAD</span><small>ARTWORK UNAVAILABLE</small></div>}
    {!visible && product.kind === 'agents' && <div className="agent-preview">{agents.slice(0, 6).map(agent => <span key={agent.id}>AGENT {String(agent.id).padStart(2, '0')}</span>)}</div>}
    {!visible && product.kind === 'image' && <div className="empty-shot"><span>SCREENSHOT<br />PLACEHOLDER</span><small>16:9 / ASSET READY</small></div>}
  </div>;
}
const SectionTitle = ({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) => <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>;
function App() { const [open, setOpen] = React.useState(false); return <><header><a className="brand" href="#top"><img src={`${import.meta.env.BASE_URL}favicon.png`} alt="" />KAC<span>KUPA</span></a><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'open' : ''}>{[['Treasury', '#treasury'], ['Goal', '#goal'], ['Products', '#products'], ['Token TBC', '#token'], ['Round Table', '#roundtable'], ['Build Log', '#build-log']].map(([label, href]) => <a href={href} onClick={() => setOpen(false)} key={label}>{label}</a>)}</nav></header>
<main id="top">
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot" /> PUBLIC BUILD / 001</p><h1>Building products. Taking fees. Stacking the roll.</h1><p className="lede">Build products → Capture fees → Feed Srajtaśma. Keep stacking rolls.</p><a className="button" href="#products">Follow the build <ArrowUpRight size={16} /></a></div><img className="hero-scene" src={`${import.meta.env.BASE_URL}assets/hero-bunker.png`} alt="Pixel frog operating a crypto treasury bunker" /></section>
<section className="metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="flywheel"><p className="eyebrow">THE BASIC IDEA</p><div>{['BUILD', 'ACTIVITY', 'FEES', 'SRAJTAŚMA', 'COMPOUND'].map((item, i) => <React.Fragment key={item}><b>{item}</b>{i < 4 && <span>→</span>}</React.Fragment>)}</div></section>
<section id="treasury" className="treasury"><div className="treasury-art"><img src={`${import.meta.env.BASE_URL}assets/treasury-vault.png`} alt="Pixel-art treasury vault with stacked rolls" /></div><SectionTitle eyebrow="01 / SRAJTAŚMA" title="The retirement roll."><p className="side-note">When shit hits the fan, you’ll wish you stacked more.</p></SectionTitle><p className="treasury-story">Product fees pile into the roll. Later, the treasury moves into productive assets and compounds.</p><div className="treasury-main"><div className="big-number"><span>TREASURY VALUE</span><strong>$0</strong><em>STARTING VALUE: $0</em></div><div className="treasury-list">{treasury.slice(1).map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><p className="roll-line">KEEP STACKING THE ROLL</p><p className="treasury-objective">The objective is simple: make this number go up.</p></section>
<section id="goal" className="goal"><div className="goal-art"><img src={`${import.meta.env.BASE_URL}assets/ecosystem-flow.png`} alt="Pixel-art ecosystem map feeding a central treasury vault" /></div><SectionTitle eyebrow="02 / THE GOAL" title="Build an ecosystem that runs autonomously." /><div className="goal-flow">PRODUCTS <span>→</span> FEES <span>→</span> LOCKED TREASURY <span>→</span> PRODUCTIVE ASSETS <span>→</span> DIVIDENDS / INCOME <span>→</span> GOVERNANCE TOKEN HOLDERS</div><div className="goal-progress">PROJECT-LED <span>→</span> AUTOMATED <span>→</span> AGENT-ASSISTED <span>→</span> GOVERNED <span>→</span> SELF-SUSTAINING</div><p className="goal-final">The destination is a self-sustaining ecosystem: products keep generating fees, the treasury keeps compounding, and governance-token holders receive the income it produces.</p></section>
<section id="products"><SectionTitle eyebrow="03 / PRODUCTS" title="Built, used, then opened up."><p className="side-note">ReadSentence and the Degen Karts prototype are live, but neither generates fees yet. ARB Launchpad and Caesar Engine are works in progress. The Round Table is planned.</p></SectionTitle><div className="global-rule">WE BUILD IT <span>→</span> WE USE IT <span>→</span> YOU CAN LAUNCH YOUR OWN <span>→</span> THE TREASURY TAKES A CUT</div><div className="product-grid">{products.map((product, i) => { const url = (product as Product & { url?: string }).url; return <article className={'product ' + (i === 2 ? 'featured' : '')} id={product.id} key={product.id}><ProductVisual product={product} /><div className="product-info"><div><span className={'status ' + product.tone}><i />{product.status}</span><h3>{product.name}</h3></div><p>{product.description}</p><div className="product-actions">{url && <a className="external-cta" href={url} target="_blank" rel="noreferrer">VISIT {product.name.toUpperCase()} <ArrowUpRight size={15} /></a>}<a href={'#' + product.id + '-details'} aria-label={'Read more about ' + product.name}>DETAILS <ArrowUpRight size={15} /></a></div></div><div className="product-details" id={product.id + '-details'}><span>{product.name.toUpperCase()}</span><p>{product.details}</p></div></article>; })}</div></section>
<section id="token" className="token"><div className="token-art"><img src={`${import.meta.env.BASE_URL}assets/round-table.png`} alt="Pixel-art Round Table strategy room" /></div><SectionTitle eyebrow="04 / SRAJTAŚMA TOKEN" title="Governance token — TBC"><p className="side-note">The coordination and ownership layer around the treasury and ecosystem.</p></SectionTitle><p className="token-lede">The future token is intended to connect the products, treasury and community through governance, participation in ecosystem economics and one common token across the product ecosystem. Over time, the system should rely less on central control.</p><div className="token-grid">{['GOVERNANCE OVER THE ECOSYSTEM', 'GOVERNANCE OVER TREASURY DECISIONS', 'PARTICIPATION IN ECOSYSTEM ECONOMICS', 'ONE COMMON TOKEN ACROSS PRODUCTS', 'PROGRESSIVE DECENTRALISATION'].map(item => <div key={item}><span>PLANNED ROLE</span><b>{item}</b></div>)}</div><div className="tbc-box"><strong>We build the revenue engine first. The token comes around something real.</strong><p>Token name / ticker: TBC · Total supply: TBC · Distribution: TBC · Launch mechanics: TBC</p></div></section>
<section id="roundtable" className="roundtable"><div className="roundtable-art"><img src={`${import.meta.env.BASE_URL}assets/round-table.png`} alt="Pixel-art Round Table strategy room" /></div><SectionTitle eyebrow="05 / THE ROUND TABLE" title="12 agents. Always working the ecosystem."><p className="side-note">ATTENTION · RESEARCH · OPPORTUNITIES</p></SectionTitle><p className="roundtable-intro">Mainly an internal advantage, not a white-label product at this stage. Detailed roles will come later.</p><div className="agents">{agents.map(agent => <div className="agent" key={agent.id}><div className="avatar"><CircleDot /></div><div><b>AGENT {String(agent.id).padStart(2, '0')}</b><span>{agent.role}</span><small><i /> OFFLINE / NOT DEPLOYED</small></div></div>)}</div></section>
<section className="model"><div className="model-art"><img src={`${import.meta.env.BASE_URL}assets/build-workshop.png`} alt="Pixel-art builder workshop with product blueprints" /></div><SectionTitle eyebrow="06 / BUILD MODEL" title="Build it. Use it. Open it." /><div className="steps">{[['01', 'BUILD IT', 'Create something the workshop actually wants to use.'], ['02', 'USE IT', 'Run it inside the ecosystem and learn what makes it useful.'], ['03', 'MAKE MONEY', 'Turn real activity into fees and sustainable revenue.'], ['04', 'OPEN IT TO OTHERS', 'Make the working product configurable for other projects.'], ['05', 'TAKE A CUT', 'Creators keep the majority while Srajtaśma receives the platform share.']].map(([number, title, description]) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></div>)}</div></section>
<section id="build-log" className="log"><SectionTitle eyebrow="07 / PUBLIC BUILD LOG" title="Watching it take shape." /><div className="log-entry"><div className="log-date">{buildLog[0].date}</div><div>{buildLog[0].items.map(item => <p key={item}><span>+</span>{item}</p>)}</div></div></section>
</main></>; }
createRoot(document.getElementById('root')!).render(<App />);
