import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, CircleDot, Menu, X } from 'lucide-react';
import { agents, buildLog, metrics, principles, products, treasury } from './data';
import './styles.css';
import './overrides.css';

type Product = (typeof products)[number];
function ProductVisual({ product }: { product: Product }) { const [visible, setVisible] = React.useState(true); const src = `${import.meta.env.BASE_URL}${product.image.replace(/^\//, '')}`; return <div className={'visual ' + product.kind}><div className="visual-label">PRODUCT SNAPSHOT <span>/{product.image.replace('/assets/', '')}</span></div>{visible && <img className="product-image" src={src} alt={`${product.name} preview`} onError={() => setVisible(false)} />}{!visible && product.kind === 'network' && <><div className="network"><div className="arb-node">ARB<br /><b>BOT</b></div>{['ROBINHOOD CHAIN', 'BASE', 'ETHEREUM L1'].map((chain, i) => <div className={'chain c' + i} key={chain}><i />{chain}<small>KACKUPA MARKET</small></div>)}</div><div className="soon">SOLANA <span>— COMING SOON</span></div></>}{!visible && product.kind === 'agents' && <div className="agent-preview">{agents.slice(0, 6).map(agent => <span key={agent.id}>AGENT {String(agent.id).padStart(2, '0')}</span>)}</div>}{!visible && product.kind === 'image' && <div className="empty-shot"><span>SCREENSHOT<br />PLACEHOLDER</span><small>16:9 / ASSET READY</small></div>}</div>; }
const SectionTitle = ({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) => <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>;
function App() { const [open, setOpen] = React.useState(false); return <><header><a className="brand" href="#top">KAC<span>KUPA</span></a><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'open' : ''}>{[['Treasury', '#treasury'], ['Goal', '#goal'], ['Products', '#products'], ['Token TBC', '#token'], ['Round Table', '#roundtable'], ['Build Log', '#build-log']].map(([label, href]) => <a href={href} onClick={() => setOpen(false)} key={label}>{label}</a>)}<a href="https://github.com/kackupa/SIPP" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14} /></a></nav></header>
<main id="top">
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot" /> PUBLIC BUILD / 001</p><h1>Turning internet nonsense into permanent capital.</h1><p className="lede">Starting from $0. I build products that capture fees from crypto activity. The fees feed Srajtaśma. Then we keep stacking the roll.</p><a className="button" href="#products">Follow the build <ArrowUpRight size={16} /></a></div><div className="hero-mark"><span>K</span><span>K</span><small>BUILD / ACTIVITY / FEES</small></div></section>
<section className="metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="flywheel"><p className="eyebrow">THE BASIC IDEA</p><div>{['BUILD', 'ACTIVITY', 'FEES', 'SRAJTAŚMA', 'COMPOUND'].map((item, i) => <React.Fragment key={item}><b>{item}</b>{i < 4 && <span>→</span>}</React.Fragment>)}</div></section>
<section id="treasury" className="treasury"><SectionTitle eyebrow="01 / SRAJTAŚMA" title="The retirement roll."><p className="side-note">When shit hits the fan, you’ll wish you stacked more.</p></SectionTitle><p className="treasury-story">Product fees pile into the roll. Later, the treasury moves into productive assets and compounds.</p><div className="treasury-main"><div className="big-number"><span>TREASURY VALUE</span><strong>$0</strong><em>STARTING VALUE: $0</em></div><div className="treasury-list">{treasury.slice(1).map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><p className="roll-line">KEEP STACKING THE ROLL</p><p className="treasury-objective">The objective is simple: make this number go up.</p></section>
<section id="goal" className="goal"><SectionTitle eyebrow="02 / THE GOAL" title="Build an ecosystem that can eventually run without me." /><div className="goal-flow">PRODUCTS <span>→</span> FEES <span>→</span> LOCKED TREASURY <span>→</span> PRODUCTIVE ASSETS <span>→</span> DIVIDENDS / INCOME <span>→</span> GOVERNANCE TOKEN HOLDERS</div><div className="goal-progress">FOUNDER-LED <span>→</span> AUTOMATED <span>→</span> AGENT-ASSISTED <span>→</span> GOVERNED <span>→</span> SELF-SUSTAINING</div><p className="goal-final">The destination is a self-sustaining ecosystem: products keep generating fees, the treasury keeps compounding, and governance-token holders receive the income it produces.</p></section>
<section id="products"><SectionTitle eyebrow="03 / PRODUCTS" title="Built, used, then opened up."><p className="side-note">ReadSentence is live. ARB Launchpad is building. Degen Karts and Caesar Engine are prototypes. The Round Table is planned.</p></SectionTitle><div className="global-rule">WE BUILD IT <span>→</span> WE USE IT <span>→</span> YOU CAN LAUNCH YOUR OWN <span>→</span> SRAJTAŚMA TAKES A CUT</div><div className="product-grid">{products.map((product, i) => { const url = (product as Product & { url?: string }).url; return <article className={'product ' + (i === 1 ? 'featured' : '')} id={product.id} key={product.id}><ProductVisual product={product} /><div className="product-info"><div><span className={'status ' + product.tone}><i />{product.status}</span><h3>{product.name}</h3></div><p>{product.description}</p><div className="product-actions">{url && <a className="external-cta" href={url} target="_blank" rel="noreferrer">VISIT READSENTENCE <ArrowUpRight size={15} /></a>}<a href={'#' + product.id + '-details'} aria-label={'Read more about ' + product.name}>DETAILS <ArrowUpRight size={15} /></a></div></div><div className="product-details" id={product.id + '-details'}><span>{product.name.toUpperCase()}</span><p>{product.details}</p></div></article>; })}</div></section>
<section id="token" className="token"><SectionTitle eyebrow="04 / SRAJTAŚMA TOKEN" title="Governance token — TBC"><p className="side-note">The coordination and ownership layer around the treasury and ecosystem.</p></SectionTitle><p className="token-lede">The future token is intended to connect the products, treasury and community through governance, participation in ecosystem economics and one common token across the product ecosystem. The system should progressively rely less on the founder.</p><div className="token-grid">{['GOVERNANCE OVER THE ECOSYSTEM', 'GOVERNANCE OVER TREASURY DECISIONS', 'PARTICIPATION IN ECOSYSTEM ECONOMICS', 'ONE COMMON TOKEN ACROSS PRODUCTS', 'PROGRESSIVE DECENTRALISATION'].map(item => <div key={item}><span>PLANNED ROLE</span><b>{item}</b></div>)}</div><div className="tbc-box"><strong>We build the revenue engine first. The token comes around something real.</strong><p>Token name / ticker: TBC · Total supply: TBC · Distribution: TBC · Launch mechanics: TBC</p></div></section>
<section id="roundtable" className="roundtable"><SectionTitle eyebrow="05 / THE ROUND TABLE" title="12 agents. Always working the ecosystem."><p className="side-note">ATTENTION · RESEARCH · OPPORTUNITIES</p></SectionTitle><p className="roundtable-intro">Mainly an internal advantage, not a white-label product at this stage. Detailed roles will come later.</p><div className="agents">{agents.map(agent => <div className="agent" key={agent.id}><div className="avatar"><CircleDot /></div><div><b>AGENT {String(agent.id).padStart(2, '0')}</b><span>{agent.role}</span><small><i /> OFFLINE / NOT DEPLOYED</small></div></div>)}</div></section>
<section className="model"><SectionTitle eyebrow="06 / BUILD MODEL" title="Build it. Use it. Open it." /><div className="steps">{[['01', 'BUILD IT', 'Create something the workshop actually wants to use.'], ['02', 'USE IT', 'Run it inside the ecosystem and learn what makes it useful.'], ['03', 'MAKE MONEY', 'Turn real activity into fees and sustainable revenue.'], ['04', 'OPEN IT TO OTHERS', 'Make the working product configurable for other projects.'], ['05', 'TAKE A CUT', 'Creators keep the majority while Srajtaśma receives the platform share.']].map(([number, title, description]) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></div>)}</div></section>
<section id="transparency" className="transparency"><SectionTitle eyebrow="07 / BUILT IN PUBLIC" title="Less trust over time."><p className="side-note">Important parts of the system should become transparent and independently verifiable.</p></SectionTitle><div className="trust-grid">{[['PUBLIC MONEY', 'Treasury balances and fee flows visible on-chain.'], ['OPEN CODE', 'Core contracts published and verifiable.'], ['CLEAR ECONOMICS', 'Fees and token mechanics visible before participation.'], ['LESS TRUST OVER TIME', 'Move control from the founder toward contracts and governance as the system matures.']].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><blockquote>I’m putting my own time, products and treasury into the same system. You can watch it being built from $0, inspect what exists, and decide for yourself whether you want to join the adventure.</blockquote></section>
<section id="build-log" className="log"><SectionTitle eyebrow="08 / PUBLIC BUILD LOG" title="Watching it take shape." /><div className="log-entry"><div className="log-date">{buildLog[0].date}</div><div>{buildLog[0].items.map(item => <p key={item}><span>+</span>{item}</p>)}</div></div></section><section id="docs" className="docs"><SectionTitle eyebrow="09 / PRINCIPLES" title="The rules of the build." /><div className="principles">{principles.map(([title, description], i) => <div key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p></div>)}</div></section>
</main><footer><span>KAC KUPA — starting from $0.</span><a href="https://github.com/kackupa/SIPP" target="_blank" rel="noreferrer">GITHUB <ArrowUpRight size={14} /></a></footer></>; }
createRoot(document.getElementById('root')!).render(<App />);
